### PR TITLE
Br2

### PR DESCRIPTION
**Pull request by agree2012**

### CODE REVIEW

**Comment by Svetoch987** [comment]
Build triggered. sha1 is merged.

**Comment by Svetoch987** [comment]
Build started sha1 is merged.

**Comment by Svetoch987** [comment]
Build finished.

**Comment by agree2012** [comment]
test this please

**Comment by agree2012** [comment]
test this please

**Comment by agree2012** [comment]
test this please

**Comment by agree2012** [comment]
test this please

**Comment by agree2012** [comment]
test this please

**Comment by agree2012** [comment]
test this please

**Comment by agree2012** [comment]
test this please

**Comment by agree2012** [comment]
test this please

**Comment by agree2012** [comment]
test this please

**Comment by agree2012** [comment]
test this please

**Comment by agree2012** [comment]
test this please

**Comment by agree2012** [comment]
test this please

**Comment by agree2012** [comment]
[72% (+71.83%) vs master 0%%20vs%20master%200%25-yellow.svg)](http://jenkins.andersenlab.com/job/DevopsTest/job/GradleUnitTest/92/)

**Comment by agree2012** [comment]
test this please

**Comment by agree2012** [comment]
[0% (0.0%) vs master 0%%20vs%20master%200%25-red.svg)](http://jenkins.andersenlab.com/job/DevopsTest/job/GradleUnitTest/94/)

**Pull request closed without merging**
